url: "https://chrisokwakol.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/jekyll-test" # the subpath of your site, e.g. /blog
title: "Matt Ralston" # the name of your site, e.g. ACME Corp.

# sass: 
#   sass_dir: _sass


# Page title
homepage: Home
portfolioPage: Portfolio